FROM python:3.11

WORKDIR '/'

COPY poregen /poregen

COPY tests /tests

COPY requirements.txt /requirements.txt

COPY setup.py /setup.py

COPY saveddata /saveddata

COPY savedmodels /savedmodels

COPY notebooks /notebooks

RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python", "scripts/20231211-test-run.py"]
