doing: []
done: []
on_queue:
- /home/dfnaiff/User/Repos/PoreGen/configs/dfn/07112024-test-battery-1.yaml
- /home/dfnaiff/User/Repos/PoreGen/configs/dfn/07112024-test-battery-2.yaml
- /home/dfnaiff/User/Repos/PoreGen/configs/dfn/07112024-test-battery-3.yaml
- /home/dfnaiff/User/Repos/PoreGen/configs/dfn/07112024-test-battery-4.yaml
