data:
  loader: 'eleven_sandstones'
  batch_size: 8
  image_size: 64
  num_workers: 41
  training_dataset_size: 34560
  validation_dataset_size: 3840
  voxel_downscale_factor: 1
  center: false
  invert: false
  dimension: 3
  psplit: 0.8
  path: ['/home/danilo/repos/PoreGen/saveddata/raw/imperial_college/Bentheimer_1000c_3p0035um.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/imperial_college/Doddington_1000c_2p6929um.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/imperial_college/Estaillades_1000c_3p31136um.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/imperial_college/Ketton_1000c_3p00006um.raw']

model:
  type: 'ldm'
  config:
    ch: 32
    num_res_blocks: 2
    dropout: 0.1
    has_mid_attn: false

training:
  kl_weight: 1e-4
  num_epochs: 150
  optimizer:
    type: 'adamw'
    lr: 5.0e-4
  scheduler:
    type: 'constant'
    num_warmup_steps: 1000
  val_check_interval: 1.0
  precision: "bf16"
  gradient_clip_val: 0.5
  save_top_k: 3
  strategy: 'auto'
  accelerator: 'gpu'
  devices: 6

output:
  folder: '/home/danilo/repos/PoreGen/savedmodels/production/20241029-bps-ldmvae-4imperial'
