data:
  loader: 'eleven_sandstones'
  batch_size: 2
  image_size: 256
  num_workers: 4
  training_dataset_size: 34560
  validation_dataset_size: 3840
  voxel_downscale_factor: 1
  center: false
  invert: false
  dimension: 3
  psplit: 0.7
  path: ['/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/BanderaBrown_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/BanderaGray_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/BB_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/Bentheimer_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/Berea_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/BSG_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/BUG_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/CastleGate_2d25um_binary.raw',
        '/home/danilo/repos/PoreGen/saveddata/raw/eleven_sandstones/Kirby_2d25um_binary.raw']
  feature_extractor: ['porosity', 'two_point_correlation_from_voxel']

model:
  type: 'PUNetG'
  config:
    input_channels: 4
    output_channels: 4
    dimension: 3
    model_channels: 64
    channel_expansion: [2, 4]
    number_resnet_downward_block: 2
    number_resnet_upward_block: 2
    number_resnet_attn_block: 0
    number_resnet_before_attn_block: 3
    number_resnet_after_attn_block: 3
    kernel_size: 3
    in_out_kernel_size: 3
    in_embedding: false
    time_projection_scale: 10.0
    input_projection_scale: 1.0
    transition_scale_factor: 2
    transition_kernel_size: 3
    dropout: 0.1
    cond_dropout: 0.1
    first_resblock_norm: 'GroupLN'
    second_resblock_norm: 'GroupRMS'
    affine_norm: true
    convolution_type: "default"
    num_groups: 1
    attn_residual: false
    attn_type: "default"
    bias: true
  params:
    conditional_embedding: ['porosity_embedder', 'tpc_transformer']
    channel_conditional_items: null
  autoencoder:
    type: 'AutoencoderKL'
    checkpoint_path: '/home/danilo/repos/PoreGen/savedmodels/production/20241029-bps-ldmvae-9sandstones/checkpoints/model-epoch=089-val_loss=0.003998.ckpt'
    resolution: 256
    has_mid_attn: false
    kl_weight: 1e-4

training:
  num_epochs: 100
  optimizer:
    type: 'adamw'
    lr: 1.0e-4
  scheduler:
    type: 'constant'
    num_warmup_steps: 1000
  val_check_interval: 1.0
  precision: "bf16"
  gradient_clip_val: 0.5
  accumulate_grad_batches: 2
  save_top_k: 3
  strategy: 'auto'
  accelerator: 'gpu'
  devices: 6
  karras_type: 'edm'
  karras_config:
    sigma_data: 0.5
    prior_mean: -1.2
    prior_std: 1.2
    has_edm_batch_norm: false
    dynamic_loss_weight: null
  conditional: true
  masked: false

output:
  folder: '/home/danilo/repos/PoreGen/savedmodels/experimental/20241101-bps-ldm-9sandstones256-porosity-tpc-cond'
