data:
  loader: 'eleven_sandstones'
  batch_size: 4
  image_size: 128
  num_workers: 64
  training_dataset_size: 34560
  validation_dataset_size: 3840
  voxel_downscale_factor: 1
  center: false
  invert: false
  dimension: 3
  psplit: 0.8
  path: '/home/danilo/repos/PoreGen/saveddata/raw/imperial_college/Estaillades_1000c_3p31136um.raw'
  voxel_size_um: 3.3

model:
  type: 'PUNetG'
  config:
    input_channels: 4
    output_channels: 4
    dimension: 3
    model_channels: 64
    channel_expansion: [2, 4]
    number_resnet_downward_block: 2
    number_resnet_upward_block: 2
    number_resnet_attn_block: 0
    number_resnet_before_attn_block: 3
    number_resnet_after_attn_block: 3
    kernel_size: 3
    in_out_kernel_size: 3
    in_embedding: false
    time_projection_scale: 10.0
    input_projection_scale: 1.0
    transition_scale_factor: 2
    transition_kernel_size: 3
    dropout: 0.1
    cond_dropout: 0.1
    first_resblock_norm: 'GroupLN'
    second_resblock_norm: 'GroupRMS'
    affine_norm: true
    convolution_type: "default"
    num_groups: 1
    attn_residual: false
    attn_type: "default"
    bias: true
  params:
    channel_conditional_items: null
  autoencoder:
    type: 'AutoencoderKL'
    checkpoint_path: '/home/danilo/repos/PoreGen/savedmodels/production/20241029-bps-ldmvae-4imperial/checkpoints/model-epoch=060-val_loss=0.002525.ckpt'
    resolution: 128
    has_mid_attn: false
    kl_weight: 1e-4

training:
  num_epochs: 80
  optimizer:
    type: 'adamw'
    lr: 2.0e-3
  scheduler:
    type: 'cosine'
    num_warmup_steps: 1000
  val_check_interval: 1.0
  precision: "bf16"
  gradient_clip_val: 0.5
  save_top_k: 3
  strategy: 'auto'
  accelerator: 'gpu'
  devices: 6
  karras_type: 'edm'
  karras_config:
    sigma_data: 0.5
    prior_mean: -0.4
    prior_std: 1.0
    has_edm_batch_norm: false
    dynamic_loss_weight: null
  conditional: false
  masked: false

output:
  folder: '/home/danilo/repos/PoreGen/savedmodels/experimental/20241114-bps-ldm-estaillades128-cosine'
