doing: /home/danilo/repos/PoreGen/configs/bps/20241217-bps-ldm-bentheimer256.yaml
done:
- /home/danilo/repos/PoreGen/configs/bps/20241205-bps-ldm-bentheimer256-por_cond.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241205-bps-ldm-bentheimer256-por_cond.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241205-bps-ldm-ketton256-por_cond.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241213-bps-ldm-ketton256-por-tpc_cond.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241216-bps-ldm-bentheimer256-por-tpc_cond.yaml
on_queue:
- /home/danilo/repos/PoreGen/configs/bps/20241216-bps-ldm-doddington128_128ch.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241216-bps-ldm-bentheimer128-por_cond.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241216-bps-ldm-ketton128-por_cond.yaml
