doing: null
done:
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-estaillades128.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-doddington128.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-estaillades256.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241122-bps-ldm-doddington128.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-bentheimer128.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-ketton128.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-doddington256.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-bentheimer256.yaml
- /home/danilo/repos/PoreGen/configs/bps/20241107-bps-ldm-ketton256.yaml
on_queue: []
