doing: /home/ubuntu/repos/PoreGen/configs/bps/20250113-bps-ldm-bentheimer256-p_tpc_cond-aws.yaml
done:
- /home/ubuntu/repos/PoreGen/configs/bps/20250106-bps-ldm-doddington256-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250108-bps-ldm-bentheimer256-p_cond-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250106-bps-ldm-bentheimer256-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250108-bps-ldm-doddington256-p_cond-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250106-bps-ldm-estaillades256-aws.yaml
on_queue:
- /home/ubuntu/repos/PoreGen/configs/bps/20250113-bps-ldm-doddington256-p_tpc_cond-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250108-bps-ldm-estaillades256-p_cond-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250114-bps-latentfree-estaillades64.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250106-bps-ldm-ketton256-aws.yaml
- /home/ubuntu/repos/PoreGen/configs/bps/20250108-bps-ldm-ketton256-p_cond-aws.yaml
