data:
  loader: 'eleven_sandstones'
  batch_size: 4
  image_size: 64
  num_workers: 4
  training_dataset_size: 34560
  validation_dataset_size: 3840
  voxel_downscale_factor: 4
  center: false
  invert: false
  dimension: 2
  psplit: 0.8
  path: '/home/dfnaiff/User/Repos/PoreGen/saveddata/raw/imperial_college/Doddington_1000c_2p6929um.raw'
  feature_extractor: ['porosity']
  feature_extractor_kwargs:
    two_point_correlation_from_voxel:
      bins: 10
model:
  type: 'PUNetG'
  config:
    input_channels: 1
    output_channels: 1
    dimension: 2
    model_channels: 16
    channel_expansion: [2, 4]
    number_resnet_downward_block: 2
    number_resnet_upward_block: 2
    number_resnet_attn_block: 0
    number_resnet_before_attn_block: 2
    number_resnet_after_attn_block: 2
    kernel_size: 3
    in_out_kernel_size: 3
    in_embedding: false
    time_projection_scale: 10.0
    input_projection_scale: 1.0
    transition_scale_factor: 2
    transition_kernel_size: 3
    dropout: 0.1
    cond_dropout: 0.1
    first_resblock_norm: 'GroupLN'
    second_resblock_norm: 'GroupRMS'
    affine_norm: true
    convolution_type: "default"
    num_groups: 1
    attn_residual: false
    attn_type: "default"
    bias: true
  params:
    conditional_embedding: ['porosity_embedder']
    channel_conditional_items: null

training:
  num_epochs: 2
  learning_rate: 2e-4
  warmup_step_percentage: 0.05
  val_check_interval: 1.0
  precision: 16
  gradient_clip_val: 0.5
  save_top_k: 3
  strategy: 'auto'
  accelerator: 'gpu'
  devices: 'auto'
  karras_type: 'edm'
  karras_config:
    sigma_data: 0.5
    prior_mean: -1.2
    prior_std: 1.2
    has_edm_batch_norm: false
  conditional: true
  masked: false

output:
  folder: '/home/dfnaiff/User/Repos/PoreNet/notebooks/exploratory/dfn/output4'
